name: Deploy content to GitHub Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry and dependencies
        uses: greenbone/actions/poetry@v2
        with:
          version: "3.10"
      - name: Build Documentation
        run: |
          cd content && poetry run nikola build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "content/output/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
